### ISSUE TITLE
Fixes to reach v0.0.2 milestone

### ISSUE THREAD

**Issue by robertamezquita** [Bioconductor/OrchestratingSingleCellAnalysis-release#10]
TODOs for v0.0.2

- re-add HCA data workflow
- change code syntax highlighting
- fix allllll the ??? references
- fix the cron job so it finds the right R build on the cluster
- rewrite multimodal data section to mention altExp; rewrite the spike-ins part in the context of altExp

@LTLA give me more todos

**Comment by robertamezquita** [comment]
- [X] re-add HCA data workflow
- [ ] change code syntax highlighting
   - tried zenburn and default; generate some example code with various highlighters to test
- [ ] fix all ??? references
- [X] fix cron job to find the right R
- [ ] rewrite multimodal data section for altExp compatibility
- [ ] add workflow that showcases multimodal analysis with CITE-seq data
   - see example data from 10X: https://support.10xgenomics.com/single-cell-vdj/datasets
- [ ] remove any triple-hashes to avoid collision with syntax highlighter
